version: '3.7'

services:
  workspace:
    build:
      context: .
      dockerfile: Dockerfile
    image: cerberus
    restart: on-failure
    container_name: cerberus
    ports:
      - ${APP_PORT}:${APP_PORT}
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    env_file:
      - .env
    networks:
      - cerberus
    tty: true
    stdin_open: true
    depends_on:
      - mysql
  mysql:
    image: mysql:latest
    restart: always
    container_name: cerberus-mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: true
      MYSQL_DATABASE: cerberus
      MYSQL_ROOT_HOST: '%'
    ports:
      - "3306:3306"
    volumes:
      - .mysql-data:/var/lib/mysql
    networks:
      - cerberus
networks:
  cerberus:
    name: cerberus
    driver: bridge
