name: Cerberus CI

on:
  push:
  pull_request:
  # schedule:
  #   - cron: "0 0 * * *"

jobs:
  build:
    name: Lint, Build and Test
    timeout-minutes: 15
    runs-on: ubuntu-latest

    services:
      postgres:
        # Docker Hub image
        image: mongo:latest
        # Provide the password for postgres
        env:
          MONGODB_DATABASE: cerberus
        ports:
          - 27017:27017

    strategy:
      matrix:
        node-version: [16.x, 18.x, 19.x]

    steps:
      - name: Check out code
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: Install dependencies
        run: npm install

      - name: Copy .env file
        working-directory: apps/api
        run: cp .env.example .env

      - name: Lint
        run: npm run lint

      - name: Build
        run: npm run build

      - name: Test
        run: npm test
        env:
          APP_KEY: ${{ secrets.APP_KEY }}
          DB_URI: "mongodb://localhost/cerberus"
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
